name: WhereIs
version: '${project.version}'
main: de.limited_dev.whereis.Main
api-version: 1.18
authors: [ limited_dev ]
description: Where is this player? /whereis <Player Name>
website: limited-dev.de

commands:
  getlocation:
    premission: whereis.command.getlocation
    aliases: [location, loc, whereis, WhereIs]
    description: Get the location of any player
  ctp:
    permission:
      whereis.command.customTp
    aliases: [customTp, customTP]
    description: A custom version of the tp command
